//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Application.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forum.Application.Resourses.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving Comment on Archived Topic Is Not Possible.
        /// </summary>
        public static string CommentArchiveDenied {
            get {
                return ResourceManager.GetString("CommentArchiveDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment With such Id was not found, or it does not belongs to current user.
        /// </summary>
        public static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such Directory Does Not Exists.
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User With Such Email Already Exists.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong While registering user.
        /// </summary>
        public static string FaildToRegister {
            get {
                return ResourceManager.GetString("FaildToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While Updating User Information Something Went Wrong.
        /// </summary>
        public static string FaildToUpdate {
            get {
                return ResourceManager.GetString("FaildToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Ban User.
        /// </summary>
        public static string FailedToBan {
            get {
                return ResourceManager.GetString("FailedToBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed file extensions are {0}.
        /// </summary>
        public static string FileExstensionNotAllowed {
            get {
                return ResourceManager.GetString("FileExstensionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image was not found.
        /// </summary>
        public static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic State Can Only Be One OF Following : Pending, Show, Hide.
        /// </summary>
        public static string NoSuchTopicState {
            get {
                return ResourceManager.GetString("NoSuchTopicState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Status Can Only Be One OF Following: Active, Inactive.
        /// </summary>
        public static string NoSuchTopicStatus {
            get {
                return ResourceManager.GetString("NoSuchTopicStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Must Be At Least 1 .
        /// </summary>
        public static string NotAllowedPageSize {
            get {
                return ResourceManager.GetString("NotAllowedPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User should have written at lest {0} Comments.
        /// </summary>
        public static string NotEnoughComments {
            get {
                return ResourceManager.GetString("NotEnoughComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such Page Does Not Exists.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character, one uppercase letter, one lowercase letter, and one number..
        /// </summary>
        public static string PasswordMust {
            get {
                return ResourceManager.GetString("PasswordMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User With Such Phone Number Already Exists.
        /// </summary>
        public static string PhoneNumberExists {
            get {
                return ResourceManager.GetString("PhoneNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong On The Server.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic With Such Id Was Not Found.
        /// </summary>
        public static string TopicNotFound {
            get {
                return ResourceManager.GetString("TopicNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User With Such Credintials Already Exists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is banned.
        /// </summary>
        public static string UserIsBanned {
            get {
                return ResourceManager.GetString("UserIsBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User With Such Username Already Exists.
        /// </summary>
        public static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User With Such Username Does Not Exists.
        /// </summary>
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User With Such Credintials Was Not Found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User With Such Password Does Not Exists.
        /// </summary>
        public static string UserPasswordNotCorrect {
            get {
                return ResourceManager.GetString("UserPasswordNotCorrect", resourceCulture);
            }
        }
    }
}
